version: '3.7'

services:

  app:
    image: grafana/grafana:10.2.0
    restart: always
    env_file:
      - ../.env
    volumes:
      - $DATA_DIR:/var/lib/grafana
      - $RESOURCE_DIR:/resource
      - $GRAFANA_INI:/etc/grafana/grafana.ini
    labels:
      - traefik.enable=true
      #- traefik.http.middlewares.ipw.ipwhitelist.sourcerange=146.102.75.0/24
      #- traefik.http.routers.grafana.middlewares=ipw@docker
      - traefik.http.routers.grafana.rule=Host(`$HOST`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=myresolver
